trigger:
  - none  # Disable default triggers

resources:
  webhooks:
    - webhook: wordpress-webhook
      connection: wordpress-service-connection

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux agent

variables:
  wordpress_url: "https://rnsetest0001-gkbudcd8gfhabgbm.centralus-01.azurewebsites.net"
  storage_account: "rnetestblob"
  container_name: "$web"
  sas_token: "sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2025-02-27T15:29:18Z&st=2025-02-27T07:29:18Z&spr=https&sig=BG5qrhlt1jxfgdjCOLC8uFb9edVjBXHEPQWZeKfZ1ic%3D"

stages:
- stage: Export_Static_Site
  displayName: 'Export Static WordPress Site'
  jobs:
  - job: ExportSite
    steps:
    - script: |
        echo "Installing Simply Static plugin..."
        sudo apt update && sudo apt install -y wget unzip
        wget https://github.com/wp-cli/wp-cli/releases/download/v2.6.0/wp-cli-2.6.0.phar -O wp
        chmod +x wp
        # mv wp /usr/local/bin/wp
        wp core download
        wp --allow-root plugin install simply-static --activate --path=/home/site/wwwroot
      displayName: 'Install and Activate Simply Static Plugin'

    - script: |
        echo "Exporting WordPress site to static files..."
        wp --allow-root simply-static generate --url=$(wordpress_url) --path=/home/site/wwwroot
      displayName: 'Export Static Files'

- stage: Deploy_Static_Site
  displayName: 'Deploy Static Site to Azure Blob'
  dependsOn: Export_Static_Site
  condition: succeeded()
  jobs:
  - job: UploadToBlob
    steps:
    - task: AzureFileCopy@4
      inputs:
        SourcePath: '/home/site/wwwroot/wp-content/uploads/simply-static/'
        azureSubscription: 'wordpress'
        Destination: 'AzureBlob'
        storage: '$(storage_account)'
        ContainerName: '$(container_name)'
        BlobPrefix: 'static-site/'
        AdditionalArgumentsForBlobCopy: '--sas-token=$(sas_token)'
      displayName: 'Upload Static Files to Azure Blob Storage'

    - script: |
        echo "Deactivating Simply Static plugin..."
        wp --allow-root plugin deactivate simply-static --path=/home/site/wwwroot
        echo "Deleting Simply Static plugin..."
        wp --allow-root plugin delete simply-static --path=/home/site/wwwroot
      displayName: 'Clean Up Plugin'