trigger:
  - none  # Disable default triggers

resources:
  webhooks:
    - webhook: wordpress-webhook
      connection: wordpress-service-connection

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Webhook triggered! Starting pipeline..."
    displayName: 'Webhook Triggered'